name: $(Major).$(Minor).$(rev:r)  # build numbering format

trigger:
  branches:
    include: [ main ] # branch names which will trigger a build
  paths:
    include: [ /Extensions/WikiUpdater ] # file paths which must match to trigger a build, cannot be a variable

pr: # will trigger on PR
  branches:
    include: [ main ] # branch names which will trigger a build
  paths:
    include: [ /Extensions/WikiUpdater ] # file paths which must match to trigger a build, cannot be a variable

resources:
  repositories: # the test data
    - repository: VSTSBuildTaskValidation
      type: git
      name: VSTSBuildTaskValidation
      branch: master

variables:
  # declared in the pipeline UI
  #  major
  #  minor
  - group:  'WIKIUpdater Extension'
    # this group includes the following variables
    #  ExtensionRoot - working folder
    #  PublisherID  - Marketplace publisher
    #  ExtensionID - Marketplace extension id
    #  vmImage - name of Azure DevOps pool to use
    #  artifactLocationName -  folder the artifact to push is stored in
    #  privateExtentionsTag - tag to show if private (else blank)
    #  taskID - Marketplace ID of task
    #  wikiFilename - name of generated docs files
    #  githubPAT - for testing
    #  AzureDevOpsPAT - for testing
stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: '$(vmImage)'
        demands: npm
      steps:
      - script: "Dummy Build"


  - stage: Public
    jobs:
    - job: Post_Publish
      pool:
        vmImage: '$(vmImage)'
      steps:

        - template: ..\..\YAMLTemplates\post-publish.yml
          parameters:
              buildNumber: $(Build.BuildNumber)
              extensionName: $(Build.DefinitionName)
